sudo: false
language: python
python:
- "3.6"
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install python-coveralls
- cp travis-ci/manage.py manage.py
script:
- pycodestyle template_preprocess
- coverage run --source=template_preprocess/ manage.py test template_preprocess
after_script:
- coveralls
before_deploy:
- find template_preprocess/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > template_preprocess/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure:
  on:
    tags: true
    python: '3.6'
