sudo: false
language: python
services:
  - memcached
python:
  - "2.7"
  - "3.6"
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install Django==1.10.*
  - pip install django-compressor
  - pip install -e .
  - cp travis-ci/manage.py manage.py
script:
  - pep8 --exclude=template_preprocess/tests template_preprocess
  - coverage run --source=template_preprocess/ manage.py test template_preprocess
after_script:
- coveralls
